apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: btngvulnvex
spec:
  crd:
    spec:
      names:
        kind: BTNGVulnVex
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package btng.vuln.vex

        violation[{"msg": msg}] {
          input.review.object.metadata.annotations["trivy.security/btng-vuln-report"] == ""
          msg := "BTNG: Missing Trivy vulnerability report"
        }

        violation[{"msg": msg}] {
          vuln := input.review.object.metadata.annotations["trivy.security/btng-vuln-report"]
          vuln == "CRITICAL"
          msg := "BTNG: CRITICAL vulnerabilities detected"
        }

        violation[{"msg": msg}] {
          vuln := input.review.object.metadata.annotations["trivy.security/btng-vex-status"]
          vuln == "HIGH_NOT_JUSTIFIED"
          msg := "BTNG: HIGH vulnerability without valid VEX justification"
        }