apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: btngsignature
spec:
  crd:
    spec:
      names:
        kind: BTNGSignatureRequired
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package btng.signature

        violation[{"msg": msg}] {
          not input.review.object.metadata.annotations["cosign.sigstore.dev/signature"]
          msg := "BTNG: Image must be signed with cosign"
        }

        violation[{"msg": msg}] {
          signature := input.review.object.metadata.annotations["cosign.sigstore.dev/signature"]
          not startswith(signature, "ME")
          msg := "BTNG: Invalid cosign signature format"
        }