apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btng-data-pvc
  namespace: btng-sovereign
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard